version: '3'

services:
  dolphinscheduler-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      - DOLPHINSCHEDULER_API_URL=http://dolphinscheduler-api:12345/dolphinscheduler/api
      - DOLPHINSCHEDULER_API_KEY=${DOLPHINSCHEDULER_API_KEY}
    networks:
      - dolphinscheduler-network
    restart: unless-stopped

networks:
  dolphinscheduler-network:
    name: dolphinscheduler-network
    driver: bridge 